
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sefa Mert
 */
public class izleme extends javax.swing.JFrame {

    Baglanti_kurma baglanti = new Baglanti_kurma();
    public long startTime;
    public long endTime;
    
    private int kullanici_id;
    private int program_id;
    private String tarih;
    private int bolum;
    
    /**
     * Creates new form izleme
     */
    public izleme(int kullanici_id,int program_id,String tarih,int bolum,double sure) {
        initComponents();
        startTime = System.nanoTime();
        String film_ismi ;
        film_ismi = baglanti.film_adi_dondur(program_id);
        film_name.setText(film_ismi);
        String izlenen_b = String.valueOf(bolum);
        izlenen_bolum.setText(izlenen_b);
        
        if (sure>0) {
            int snsure = (int) sure;
            Devam_edilen_sure.setText(snsure + ".saniyeden izlemeye devam etmektesiniz...");
            
        } else {
            Devam_edilen_sure.setText("Film'e yeni baslandi.....");
        }
        
        this.kullanici_id = kullanici_id;
        this.program_id = program_id;
        this.bolum = bolum;
        this.tarih = tarih;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buton_grup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        on_radio = new javax.swing.JRadioButton();
        dokuz_radio = new javax.swing.JRadioButton();
        sekiz_radio = new javax.swing.JRadioButton();
        yedi_radio = new javax.swing.JRadioButton();
        alti_radio = new javax.swing.JRadioButton();
        bes_radio = new javax.swing.JRadioButton();
        dort_radio = new javax.swing.JRadioButton();
        uc_radio = new javax.swing.JRadioButton();
        iki_radio = new javax.swing.JRadioButton();
        bir_radio = new javax.swing.JRadioButton();
        cikis = new javax.swing.JButton();
        mesaj_kutusu = new javax.swing.JLabel();
        durdur = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        film_name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        izlenen_bolum = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Devam_edilen_sure = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        on_radio.setBackground(new java.awt.Color(0, 0, 0));
        buton_grup.add(on_radio);
        on_radio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        on_radio.setForeground(new java.awt.Color(255, 255, 255));
        on_radio.setText("10");
        jPanel1.add(on_radio);
        on_radio.setBounds(40, 330, 50, 25);

        dokuz_radio.setBackground(new java.awt.Color(0, 0, 0));
        buton_grup.add(dokuz_radio);
        dokuz_radio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        dokuz_radio.setForeground(new java.awt.Color(255, 255, 255));
        dokuz_radio.setText("9");
        jPanel1.add(dokuz_radio);
        dokuz_radio.setBounds(40, 300, 50, 25);

        sekiz_radio.setBackground(new java.awt.Color(0, 0, 0));
        buton_grup.add(sekiz_radio);
        sekiz_radio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sekiz_radio.setForeground(new java.awt.Color(255, 255, 255));
        sekiz_radio.setText("8");
        jPanel1.add(sekiz_radio);
        sekiz_radio.setBounds(40, 270, 50, 25);

        yedi_radio.setBackground(new java.awt.Color(0, 0, 0));
        buton_grup.add(yedi_radio);
        yedi_radio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        yedi_radio.setForeground(new java.awt.Color(255, 255, 255));
        yedi_radio.setText("7");
        jPanel1.add(yedi_radio);
        yedi_radio.setBounds(40, 240, 50, 25);

        alti_radio.setBackground(new java.awt.Color(0, 0, 0));
        buton_grup.add(alti_radio);
        alti_radio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        alti_radio.setForeground(new java.awt.Color(255, 255, 255));
        alti_radio.setText("6");
        jPanel1.add(alti_radio);
        alti_radio.setBounds(40, 210, 50, 25);

        bes_radio.setBackground(new java.awt.Color(0, 0, 0));
        buton_grup.add(bes_radio);
        bes_radio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bes_radio.setForeground(new java.awt.Color(255, 255, 255));
        bes_radio.setText("5");
        jPanel1.add(bes_radio);
        bes_radio.setBounds(40, 180, 50, 25);

        dort_radio.setBackground(new java.awt.Color(0, 0, 0));
        buton_grup.add(dort_radio);
        dort_radio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        dort_radio.setForeground(new java.awt.Color(255, 255, 255));
        dort_radio.setText("4");
        jPanel1.add(dort_radio);
        dort_radio.setBounds(40, 150, 50, 25);

        uc_radio.setBackground(new java.awt.Color(0, 0, 0));
        buton_grup.add(uc_radio);
        uc_radio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        uc_radio.setForeground(new java.awt.Color(255, 255, 255));
        uc_radio.setText("3");
        jPanel1.add(uc_radio);
        uc_radio.setBounds(40, 120, 50, 25);

        iki_radio.setBackground(new java.awt.Color(0, 0, 0));
        buton_grup.add(iki_radio);
        iki_radio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        iki_radio.setForeground(new java.awt.Color(255, 255, 255));
        iki_radio.setText("2");
        jPanel1.add(iki_radio);
        iki_radio.setBounds(40, 90, 50, 25);

        bir_radio.setBackground(new java.awt.Color(0, 0, 0));
        buton_grup.add(bir_radio);
        bir_radio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bir_radio.setForeground(new java.awt.Color(255, 255, 255));
        bir_radio.setText("1");
        jPanel1.add(bir_radio);
        bir_radio.setBounds(40, 60, 50, 25);

        cikis.setBackground(new java.awt.Color(255, 0, 0));
        cikis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-48.png"))); // NOI18N
        cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisActionPerformed(evt);
            }
        });
        jPanel1.add(cikis);
        cikis.setBounds(810, 10, 34, 34);

        mesaj_kutusu.setBackground(new java.awt.Color(0, 0, 0));
        mesaj_kutusu.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        mesaj_kutusu.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(mesaj_kutusu);
        mesaj_kutusu.setBounds(190, 290, 550, 40);

        durdur.setBackground(new java.awt.Color(46, 204, 113));
        durdur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        durdur.setForeground(new java.awt.Color(255, 255, 255));
        durdur.setText("DURDUR");
        durdur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durdurActionPerformed(evt);
            }
        });
        jPanel1.add(durdur);
        durdur.setBounds(360, 340, 220, 48);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FILM IZLENIYOR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 20, 546, 104);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Film Adi :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 170, 70, 30);

        film_name.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        film_name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(film_name);
        film_name.setBounds(380, 170, 220, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Izlenen Bolum :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 210, 120, 30);

        izlenen_bolum.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        izlenen_bolum.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(izlenen_bolum);
        izlenen_bolum.setBounds(380, 210, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Devam Edilen Sure :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 250, 170, 30);

        Devam_edilen_sure.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Devam_edilen_sure.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Devam_edilen_sure);
        Devam_edilen_sure.setBounds(380, 250, 380, 30);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Puan Verin :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 20, 140, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-minimize-window-48.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(770, 10, 34, 34);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pause-48.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 340, 48, 48);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 450);

        setSize(new java.awt.Dimension(874, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void durdurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durdurActionPerformed
        //String puan_degeri = verilen_puan.getText();
        
        int a = 0;
        String puan_degeri = null;
        
        if(bir_radio.isSelected()){
            puan_degeri = "1";
            a++;
        }
        else if(iki_radio.isSelected()){
            puan_degeri = "2";
            a++;
        }
        else if(uc_radio.isSelected()){
            puan_degeri = "3";
            a++;
        }
        else if(dort_radio.isSelected()){
            puan_degeri = "4";
            a++;
        }
        else if(bes_radio.isSelected()){
            puan_degeri = "5";
            a++;
        }
        else if(alti_radio.isSelected()){
            puan_degeri = "6";
            a++;
        }
        else if(yedi_radio.isSelected()){
            puan_degeri = "7";
            a++;
        }
        else if(sekiz_radio.isSelected()){
            puan_degeri = "8";
            a++;
        }
        else if(dokuz_radio.isSelected()){
            puan_degeri = "9";
            a++;
        }
        else if(on_radio.isSelected()){
            puan_degeri = "10";
            a++;
        }
        
        
        if (a == 0) {
            mesaj_kutusu.setText("Lutfen programi bitirmeden önce bir puan veriniz!!");
        } else {
            
            int puan = Integer.parseInt(puan_degeri);

            endTime = System.nanoTime();
            long estimatedTime = endTime - startTime;
            double seconds = (float)estimatedTime/1000000000;
        

            /*System.out.println("kullanici_id : " + kullanici_id);
            System.out.println("program_id : " + programid);
            System.out.println(df.format(simdikiZaman));
            System.out.println("gecen zaman : " + seconds);
            
            System.out.println("verilen puan :" + puan);           
        */
            int gercek_sure = (int) seconds;
            boolean kontrol = baglanti.program_id_kullanici_id_kontrol( kullanici_id ,program_id ,bolum);
            
            if (kontrol) {
                System.out.println("bu vardir");
                
                int sure = baglanti.izleme_suresi_bul(kullanici_id, program_id, bolum);
                System.out.println(sure);
                
                gercek_sure = gercek_sure + sure;
                
                baglanti.sure_guncelle(kullanici_id, program_id, bolum, gercek_sure);
                baglanti.puan_guncelle(kullanici_id, program_id, bolum, puan);
                baglanti.puanDegistir(program_id);
            
            } else {
                System.out.println("yoktur!!!");
                          
                baglanti.kullanici_program_ekle(kullanici_id, program_id, tarih, gercek_sure, bolum, puan);
                baglanti.puanDegistir(program_id);
                           
            }
            
            setVisible(false);
            
            
        }
    }//GEN-LAST:event_durdurActionPerformed

    private void cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisActionPerformed
        //String puan_degeri = verilen_puan.getText();
        int a = 0;
        String puan_degeri = null;
        if(bir_radio.isSelected()){
            puan_degeri = "1";
            a++;
        }
        else if(iki_radio.isSelected()){
            puan_degeri = "2";
            a++;
        }
        else if(uc_radio.isSelected()){
            puan_degeri = "3";
            a++;
        }
        else if(dort_radio.isSelected()){
            puan_degeri = "4";
            a++;
        }
        else if(bes_radio.isSelected()){
            puan_degeri = "5";
            a++;
        }
        else if(alti_radio.isSelected()){
            puan_degeri = "6";
            a++;
        }
        else if(yedi_radio.isSelected()){
            puan_degeri = "7";
            a++;
        }
        else if(sekiz_radio.isSelected()){
            puan_degeri = "8";
            a++;
        }
        else if(dokuz_radio.isSelected()){
            puan_degeri = "9";
            a++;
        }
        else if(on_radio.isSelected()){
            puan_degeri = "10";
            a++;
        }
        
        //verilen_puan.getText().equals(""))
        if (a == 0) {
            mesaj_kutusu.setText("Lutfen programi bitirmeden önce bir puan veriniz!!");
            
        } else {
            System.out.println("sdfn");
            
            int puan = Integer.parseInt(puan_degeri);

            endTime = System.nanoTime();
            long estimatedTime = endTime - startTime;
            double seconds = (float)estimatedTime/1000000000;
        

            /*System.out.println("kullanici_id : " + kullanici_id);
            System.out.println("program_id : " + programid);
            System.out.println(df.format(simdikiZaman));
            System.out.println("gecen zaman : " + seconds);
            
            System.out.println("verilen puan :" + puan);           
        */
            int gercek_sure = (int) seconds;
            boolean kontrol = baglanti.program_id_kullanici_id_kontrol( kullanici_id ,program_id ,bolum);
            
            if (kontrol) {
                System.out.println("bu vardir");
                
                int sure = baglanti.izleme_suresi_bul(kullanici_id, program_id, bolum);
                System.out.println(sure);
                
                gercek_sure = gercek_sure + sure;
                
                baglanti.sure_guncelle(kullanici_id, program_id, bolum, gercek_sure);
                baglanti.puan_guncelle(kullanici_id, program_id, bolum, puan);
                baglanti.puanDegistir(program_id);
            
            } else {
                System.out.println("yoktur!!!");
                          
                baglanti.kullanici_program_ekle(kullanici_id, program_id, tarih, gercek_sure, bolum, puan);
                baglanti.puanDegistir(program_id);
                           
            }
            
            setVisible(false);
            
            
        }
    }//GEN-LAST:event_cikisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(izleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(izleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(izleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(izleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new izleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Devam_edilen_sure;
    private javax.swing.JRadioButton alti_radio;
    private javax.swing.JRadioButton bes_radio;
    private javax.swing.JRadioButton bir_radio;
    private javax.swing.ButtonGroup buton_grup;
    private javax.swing.JButton cikis;
    private javax.swing.JRadioButton dokuz_radio;
    private javax.swing.JRadioButton dort_radio;
    private javax.swing.JButton durdur;
    private javax.swing.JLabel film_name;
    private javax.swing.JRadioButton iki_radio;
    private javax.swing.JLabel izlenen_bolum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mesaj_kutusu;
    private javax.swing.JRadioButton on_radio;
    private javax.swing.JRadioButton sekiz_radio;
    private javax.swing.JRadioButton uc_radio;
    private javax.swing.JRadioButton yedi_radio;
    // End of variables declaration//GEN-END:variables
}
