
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sefa Mert
 */
public class sevilen_tur_sergile extends javax.swing.JFrame {
    DefaultTableModel model;
    Baglanti_kurma baglanti = new Baglanti_kurma();

    /**
     * Creates new form sevilen_tur_sergile
     */
    public sevilen_tur_sergile(String birincitur, String ikincitur, String ucunucutur) {
        initComponents();
        setSize(770, 500);
        model = (DefaultTableModel) sevilen_tur_tablosu.getModel();
        sevilen_tur_goster(birincitur, ikincitur, ucunucutur);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sevilen_tur_tablosu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Giris_ekran_butonu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        sevilen_tur_tablosu.setBackground(new java.awt.Color(0, 0, 0));
        sevilen_tur_tablosu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sevilen_tur_tablosu.setForeground(new java.awt.Color(255, 255, 255));
        sevilen_tur_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PROGRAM", "TIP", "BOLUM", "PUAN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sevilen_tur_tablosu.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jScrollPane1.setViewportView(sevilen_tur_tablosu);
        if (sevilen_tur_tablosu.getColumnModel().getColumnCount() > 0) {
            sevilen_tur_tablosu.getColumnModel().getColumn(0).setResizable(false);
            sevilen_tur_tablosu.getColumnModel().getColumn(1).setResizable(false);
            sevilen_tur_tablosu.getColumnModel().getColumn(2).setResizable(false);
            sevilen_tur_tablosu.getColumnModel().getColumn(3).setResizable(false);
            sevilen_tur_tablosu.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 170, 680, 160);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("En Cok Puan Alan 6 Program :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 130, 290, 22);

        Giris_ekran_butonu.setBackground(new java.awt.Color(0, 0, 0));
        Giris_ekran_butonu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Giris_ekran_butonu.setForeground(new java.awt.Color(255, 255, 255));
        Giris_ekran_butonu.setText("Giris Ekranina Don");
        Giris_ekran_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Giris_ekran_butonuActionPerformed(evt);
            }
        });
        jPanel1.add(Giris_ekran_butonu);
        Giris_ekran_butonu.setBounds(140, 30, 157, 64);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("NETFLIX");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 70, 230, 50);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-48.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(670, 10, 36, 36);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-exit-64 (1).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 30, 64, 64);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-minimize-window-48.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(630, 10, 34, 34);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 820, 500);

        setSize(new java.awt.Dimension(845, 495));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Giris_ekran_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Giris_ekran_butonuActionPerformed
        setVisible(false);
        Giris_Ekrani ge = new Giris_Ekrani();
        ge.setVisible(true);
    }//GEN-LAST:event_Giris_ekran_butonuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        Giris_Ekrani ge = new Giris_Ekrani();
        ge.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void sevilen_tur_goster(String birincitur, String ikincitur, String ucunucutur){
        model.setRowCount(0);
        
        ArrayList<sevilen_tur> sevilen_turlar = new ArrayList<sevilen_tur>();
        
        sevilen_turlar = baglanti.sevilen_turler_getir(birincitur, ikincitur, ucunucutur);
        
        if(sevilen_turlar != null){
            for(sevilen_tur sv : sevilen_turlar){
                Object[] eklenecek = {sv.getId(), sv.getProgram_ismi(), sv.getProgram_tipi(), sv.getBolum(), sv.getPuan()};
                
                model.addRow(eklenecek);
            }
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sevilen_tur_sergile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sevilen_tur_sergile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sevilen_tur_sergile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sevilen_tur_sergile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new sevilen_tur_sergile().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Giris_ekran_butonu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable sevilen_tur_tablosu;
    // End of variables declaration//GEN-END:variables
}
